sudo: false
language: go
go:
  - "1.12.x"
script:
  - GO111MODULE=on go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - GO111MODULE=on go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)